[package]
name = "rustywiki"
version = "0.1.0 alpha"
authors = ["rustywiki team"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0"
actix-files = "0.2.1"
actix-service = "1.0.5"
listenfd = "0.3"